version: 2
updates:
  - commit-message:
      prefix: chore
    directory: /backend-acceptance-testing
    package-ecosystem: docker
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/backend-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /backend-acceptance-testing
    open-pull-requests-limit: 20
    package-ecosystem: pip
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/backend-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /backend-integration-testing
    package-ecosystem: docker
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/backend-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /backend-integration-testing
    open-pull-requests-limit: 20
    package-ecosystem: pip
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/backend-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /gui-e2e-testing
    package-ecosystem: docker
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/frontend-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /mender-client-acceptance-testing
    package-ecosystem: docker
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /mender-client-acceptance-testing
    open-pull-requests-limit: 20
    package-ecosystem: pip
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /docker/docker-files-raspbian
    package-ecosystem: docker
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /aws-k8s-toolbox
    package-ecosystem: docker
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/qa-dependabot-reviewers"
