image: docker:git

variables:
  RASPBIAN_VERSION: '2019-04-08'
  DOCKER_REPOSITORY: mendersoftware/mender-test-containers

stages:
  - test
  - build_prep
  - build
  - publish

test:
  stage: test
  before_script:
    - apk add --no-cache bash
    # Rename the branch we're on, so that it's not in the way for the
    # subsequent fetch. It's ok if this fails, it just means we're not on any
    # branch.
    - git branch -m temp-branch || true
    # Git trick: Fetch directly into our local branches instead of remote
    # branches.
    - git fetch origin 'refs/heads/*:refs/heads/*'
    # Get last remaining tags, if any.
    - git fetch --tags origin
    - git clone http://github.com/mendersoftware/mendertesting
  script:
    # Check commit compliance.
    - mendertesting/check_commits.sh

build_prep:
  stage: build_prep
  image: buildpack-deps:scm
  script:
    - cd docker/docker-files-raspbian
    - apt-get update && apt-get install -yyq sudo unzip
    - ./prepare-raspbian-img.sh ${RASPBIAN_VERSION}
    - cd .. && tar -cvf $CI_PROJECT_DIR/docker-files-raspbian.tar docker-files-raspbian
  artifacts:
    expire_in: 2w
    paths:
      - docker-files-raspbian.tar
  tags:
    - mender-qa-slave

build:
  stage: build
  dependencies:
    - build_prep
  services:
    - docker:dind
  script:
    - tar -xvf docker-files-raspbian.tar
    - docker build --build-arg raspbian_version=${RASPBIAN_VERSION} -t $DOCKER_REPOSITORY:pr docker-files-raspbian
    - docker save $DOCKER_REPOSITORY:pr > image.tar
  artifacts:
    expire_in: 2w
    paths:
      - image.tar

publish:build:master:
  before_script: []
  stage: publish
  dependencies:
    - build
  services:
    - docker:dind
  script:
    - echo "publishing image to docker hub"
    # - docker load -i image.tar
    # - export COMMIT_TAG="$CI_COMMIT_REF_NAME"_"$CI_COMMIT_SHA";
    # - docker tag $DOCKER_REPOSITORY:pr $DOCKER_REPOSITORY:$COMMIT_TAG;
    # - docker push $DOCKER_REPOSITORY:$COMMIT_TAG;
  only:
    - master
  tags:
    - docker
